-- MySQL Script generated by MySQL Workbench
-- 05/17/18 15:01:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

-- -----------------------------------------------------
-- Schema shareride
-- -----------------------------------------------------
-- Database schema for Shareride Inc. Ride application.
DROP SCHEMA IF EXISTS `shareride` ;

-- -----------------------------------------------------
-- Schema shareride
--
-- Database schema for Shareride Inc. Ride application.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shareride` DEFAULT CHARACTER SET utf8 COLLATE utf8_swedish_ci ;
USE `shareride` ;

-- -----------------------------------------------------
-- Table `shareride`.`tbl_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shareride`.`tbl_user` ;

CREATE TABLE IF NOT EXISTS `shareride`.`tbl_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique user identifier.',
  `firstName` VARCHAR(45) NOT NULL COMMENT 'Given name.',
  `lastName` VARCHAR(45) NOT NULL COMMENT 'Family name.',
  `gender` TINYINT(1) NOT NULL COMMENT 'Gender: male=0, female=1, other=2',
  `password` VARCHAR(60) NOT NULL COMMENT 'This user\'s password in a hashed form.',
  `emailAddress` VARCHAR(45) NOT NULL UNIQUE COMMENT 'User\'s email address.',
  `telephone` VARCHAR(45) NOT NULL COMMENT 'User\'s phone number.',
  `role` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Describes the type of user: administrator = 0, normal user = 1.\nBy default, the role is 1(normal user).',
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Describes the status of the user account in the system: active = 0, disabled = 1',
  `profileImage` VARCHAR(60) NULL DEFAULT 'default.png',
  `lastAccess` DATETIME NULL DEFAULT NULL,
  `lastIP` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shareride`.`tbl_vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shareride`.`tbl_vehicle` ;

CREATE TABLE IF NOT EXISTS `shareride`.`tbl_vehicle` (
  `regNumber` VARCHAR(10) NOT NULL COMMENT 'Number plate: the unique identifier for every vehicle.',
  `model` VARCHAR(45) NOT NULL,
  `capacity` INT(2) NOT NULL COMMENT 'Number of seats in the vehicle.',
  `driver` INT NOT NULL COMMENT 'A vehicle must have a driver.',
  UNIQUE INDEX `regNumber_UNIQUE` (`regNumber` ASC),
  PRIMARY KEY (`regNumber`, `driver`),
  INDEX `fk_tbl_vehicle_tbl_user_idx` (`driver` ASC),
  CONSTRAINT `fk_tbl_vehicle_tbl_user`
    FOREIGN KEY (`driver`)
    REFERENCES `shareride`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shareride`.`tbl_ride`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shareride`.`tbl_ride` ;

CREATE TABLE IF NOT EXISTS `shareride`.`tbl_ride` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'A unique identifier for the ride.',
  `origin` VARCHAR(45) NOT NULL,
  `destination` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Ride status: Future = 0, Past = 1',
  `dateOffered` DATETIME NOT NULL,
  `vehicle` VARCHAR(10) NOT NULL,
  `driver` INT NOT NULL COMMENT 'Driver for the ride.',
  PRIMARY KEY (`id`, `vehicle`, `driver`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tbl_ride_tbl_vehicle1_idx` (`vehicle` ASC, `driver` ASC),
  CONSTRAINT `fk_tbl_ride_tbl_vehicle1`
    FOREIGN KEY (`vehicle` , `driver`)
    REFERENCES `shareride`.`tbl_vehicle` (`regNumber` , `driver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shareride`.`tbl_booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shareride`.`tbl_booking` ;

CREATE TABLE IF NOT EXISTS `shareride`.`tbl_booking` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for every booking.',
  `dateBooked` DATETIME NOT NULL COMMENT 'Describes the date when a booking was made.',
  `ride` INT NOT NULL COMMENT 'Unique ride identifier for the ride being booked.',
  `user` INT NOT NULL COMMENT 'Unique identifier for the user who makes the booking.',
  PRIMARY KEY (`id`, `ride`, `user`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tbl_booking_tbl_ride1_idx` (`ride` ASC),
  INDEX `fk_tbl_booking_tbl_user1_idx` (`user` ASC),
  CONSTRAINT `fk_tbl_booking_tbl_ride1`
    FOREIGN KEY (`ride`)
    REFERENCES `shareride`.`tbl_ride` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_booking_tbl_user1`
    FOREIGN KEY (`user`)
    REFERENCES `shareride`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
